---
- name: A changement management playbook for docker daemon
  hosts: "{{ __target__ | default('all') }}"
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - casecommons.packages
    - casecommons.files
    - casecommons.secrets
    - casecommons.docker
